---
title: "5xBOAT_snRNAseq_Data_Visualization"
author: "Joshua Samuels"
date: "11/14/2022"
output: html_document
---


#### Load Packages

```{r, message=FALSE, warning=FALSE}
# Load Packages
library(Seurat)
library(tidyverse)
library(Matrix)
library(scales)
library(cowplot)
library(RCurl)
library(ggridges)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(magrittr)
library(patchwork)
library(ggraph)
library(clustree)
library(metap)
library(limma)
```


#### Load data
```{r}
vis_seurat <-readRDS(
  "D:/Research/UVA_NGP_PhD/Lukens_Lab/Experiments/BOAT_MG_KO/Phenotype_Exploration/snRNAseq/RStudio_SeuratObjects/seurat_clustered_10.28.22.rds")

# vis_seurat <- seurat_clustered_labeled
```


#### Visualize Data

##### Add data
```{r}
# Add new column to metadata containing the cell type name for each cluster
vis_seurat$cell_type <- paste(Idents(vis_seurat))
```


##### Heatmap
```{r}
# Set features to test - these are signature genes identified for all of the clusters
full_seurat_sig_genes <- c(
  "Tafa1", "Lingo2", "Lrrtm4", "Kcnip4",
  "Hs6st3", "Ptprd", "Cdh12", "Car10",
  "Gpc5", "Slc1a2", "Slc1a3", "Prex2",
  "Hs3st4", "Cdh18", "Zfpm2", "Frmpd4",
  "Plp1", "Mbp", "St18", "Mobp",
  "Lrmda", "Dock8", "Hexb", "Csf1r",
  "Nxph1", "Grip1", "Sox6", "Kcnmb2",
  "Pbx3", "Meis2", "Dpp6", "Pcbp3",
  "Adarb2", "Erbb4", "Galntl6", "Sox2ot",
  "Ptgds", "Atp1a2", "Ranbp3l", "Cped1",
  "Pdgfra", "Vcan", "Ptprz1", "Lhfpl3",
  "Rarb", "Rgs9", "Ryr3", "Kcnab1",
  "Gm2164", "Pex5l", "Hcn1", "Robo1",
  "Tshz2", "Vwc2l", "Olfm3",
  "Cldn5", "Flt1", "Slco1a4", "Mecom",
  "Ntng2", "Col11a1", "Gnb4", "Tmem163", "Cadps2",
  "Ebf1", "Atp13a5", "Pdgfrb", "Vtn"
)

# set the colors used for each cluster in the heatmap - these colors will be used as the color bar above the heatmap and correspond to the colors used in the colored UMAP
full_seurat_colors <- c(
        "skyblue1",
        "lightcoral",
        "palegreen",
        "violet",
        "sandybrown",
        "cyan",
        "peachpuff3",
        "slateblue1",
        "lightpink",
        "firebrick1",
        "green",
        "lightcyan2",
        "palevioletred",
        "darkseagreen2",
        "chocolate3",
        "grey75",
        "yellow"
)
```


```{r}
# Making the heatmap for all clusters

# Make Integrated the default assay (it contains all of the genetic data in scale.data)
DefaultAssay(vis_seurat) <- "integrated"

# Run HeatMap for all_features (remove the NoLegend function if a legend is desired) - any genes not identified will not be used
# I am downsampling to make this run faster and so the columns all are equal in width
full_seurat_heatmap <- DoHeatmap(subset(vis_seurat, downsample = 150), features = full_seurat_sig_genes, label = F, group.colors = full_seurat_colors, draw.lines = F) + 
  guides(fill = guide_colorbar(barwidth = 0.5, barheight = 10, label = F, ticks = F)) +
  theme(axis.text.y = element_text(size = 7), axis.title.x = element_text(size = 7, angle = 0)) + 
  scale_fill_gradientn(colors = c("navyblue", "ghostwhite", "brown2"))
full_seurat_heatmap
```


```{r}
# Save last plot that was printed
# Before saving, set your size and dpi (quality)
# ggsave("FileName.FileType", path = "path/path", width = , height = , units = "cm", dpi = 500)

ggsave("fullHeatmap.tiff", 
       path = "D:/Research/UVA_NGP_PhD/Lukens_Lab/Experiments/BOAT_MG_KO/Phenotype_Exploration/snRNAseq/RStudio_SeuratDataFiles/Heatmaps/", 
       dpi = 500)
```


##### Dotplot (microglia)
```{r}
# Load object
MG_seurat <-readRDS(
  "D:/Research/UVA_NGP_PhD/Lukens_Lab/Experiments/BOAT_MG_KO/Phenotype_Exploration/snRNAseq/RStudio_SeuratObjects/MGsubset_seurat_clustered_labeled_11.15.22.rds")

MG_seurat <- RenameIdents(MG_seurat, 
                               "Microglia 1" = "0",
                               "Microglia 2" = "1",
                               "Microglia 3" = "2",
                               "Border-Associated Macropage" = "3")
MG_Genes <- c(
  "Lrmda",
  "Ctsb", "Ctsd", "Apoe", "Trem2", "Myo1e", "Mertk",
  "Cx3cr1", "P2ry12", "Hexb", "Csf1r", "Dock8",
  "Tgfbr1",
  "Mrc1", "F13a1"
)

MG_seurat_colors <- c(
        "skyblue1",
        "lightcoral",
        "palegreen",
        "violet")

MG_Dotplot <- DotPlot(MG_seurat, features = c(MG_Genes), 
        # group.by = "sample",
        cols = c("lightgrey", "red3"),
        assay = "RNA") + RotatedAxis()
MG_Dotplot
```

```{r}
# Save last plot that was printed
# Before saving, set your size and dpi (quality)
# ggsave("FileName.FileType", path = "path/path", width = , height = , units = "cm", dpi = 500)

ggsave("MG_Dotplot_11.16.22.tiff", 
       path = "D:/Research/UVA_NGP_PhD/Lukens_Lab/Experiments/BOAT_MG_KO/Phenotype_Exploration/snRNAseq/RStudio_SeuratDataFiles/Dotplots/", 
       dpi = 500, height = 3.5, width = )
```
